version: 2.1
orbs:
  codecov: codecov/codecov@4.2.0
executors:
  test-executor:
    docker:
      - image: cimg/node:20.12.2
jobs:
  test:
    executor: test-executor
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
      - run: npm run test
      - codecov/upload
workflows:
  main:
    jobs:
      - test
